# Generated by Django 4.1.7 on 2023-03-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('register', models.IntegerField()),
                ('roll_no', models.IntegerField()),
                ('age', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('department', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('mail', models.CharField(max_length=200)),
                ('aadhaar_no', models.IntegerField()),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_phone', models.IntegerField()),
                ('mother_phone', models.IntegerField()),
            ],
        ),
    ]
