# Generated by Django 4.1.7 on 2023-03-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('DOB', models.DateField(null=True)),
                ('phone', models.IntegerField()),
                ('department', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dob',
        ),
        migrations.AddField(
            model_name='student',
            name='DOB',
            field=models.DateField(null=True),
        ),
    ]
