# Generated by Django 4.1.7 on 2023-03-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staff_rename_mail_student_email_remove_student_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electrical and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('Mech', 'Mechanical Engineering'), ('Civil', 'Civil Engineering')], max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electrical and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('Mech', 'Mechanical Engineering'), ('Civil', 'Civil Engineering')], max_length=200),
        ),
    ]
