# Generated by Django 4.1.7 on 2023-03-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_staff_department_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('Mech', 'Mechanical Engineering'), ('Civil', 'Civil Engineering')], max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronic Engineering'), ('Mech', 'Mechanical Engineering'), ('Civil', 'Civil Engineering')], max_length=200),
        ),
    ]
