# Generated by Django 4.1.7 on 2023-03-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_student_admission_date_student_admission_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Door_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Emergency_contact',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Local Guardian', 'Local Guardian')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian_Address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian_is',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Local Guardian', 'Local Guardian')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian_mobile',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Mother_Occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Occupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Street_and_Village',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
