# Generated by Django 4.1.7 on 2023-03-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_student_country_student_door_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Guardian_2_Address',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian_2_is',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Local Guardian', 'Local Guardian'), ('Local Guardian 2', 'Local Guardian 2')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian_2_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Guardian_2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Emergency_contact',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Local Guardian', 'Local Guardian'), ('Local Guardian 2', 'Local Guardian 2')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Guardian_is',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Local Guardian', 'Local Guardian'), ('Local Guardian 2', 'Local Guardian 2')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Guardian_mobile',
            field=models.IntegerField(null=True),
        ),
    ]
