# Generated by Django 4.1.7 on 2023-03-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_student_guardian_2_address_student_guardian_2_is_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='name',
            new_name='Employee_name',
        ),
        migrations.AddField(
            model_name='staff',
            name='Date_of_Joining',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Employee_Category',
            field=models.CharField(choices=[('Assistant professor', 'Assistant professor'), ('Professor', 'Professor'), ('Lab Staff', 'Lab Staff'), ('Supporting Staff', 'Supporting Staff'), ('Driver', 'Driver'), ('Maintenance Staff', 'Maintenance Staff')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Employee_ID',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Third', 'third')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Annual_income',
            field=models.IntegerField(null=True),
        ),
    ]
