# Generated by Django 4.1.7 on 2023-03-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_department_staff_department_staff_blood_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Street_and_Village',
            new_name='Office_Street_and_Area',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='Street_and_Village',
            new_name='Street_and_Area',
        ),
        migrations.AddField(
            model_name='staff',
            name='Children_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Office_Country',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Office_District',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Office_Door_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Office_Pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Office_State',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Street_and_Area',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
