# Generated by Django 4.1.7 on 2023-03-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_street_and_village_staff_office_street_and_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='aadhaar_no',
            new_name='Aadhaar_no',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='aadhaar_no',
            new_name='Aadhaar_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='blood_group',
            new_name='Blood_group',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='department',
            new_name='Department',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_name',
            new_name='Father_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='father_phone',
            new_name='Father_phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='gender',
            new_name='Gender',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_name',
            new_name='Mother_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_phone',
            new_name='Mother_phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='register',
            new_name='Register',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='Roll_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='year',
            new_name='Year',
        ),
        migrations.AddField(
            model_name='staff',
            name='Emergency_contact',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Home_contact_No',
            field=models.IntegerField(max_length=15, null=True),
        ),
    ]
