# Generated by Django 4.1.7 on 2023-03-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_subject_department_alter_subject_regulation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical and Electronic Engineering', 'EEE'), ('Mechanical Engineering', 'Mech'), ('Civil Engineering', 'Civil')], default='CSE', max_length=200),
        ),
        migrations.AddField(
            model_name='timetable',
            name='regulation',
            field=models.CharField(choices=[('2017 regulation', '2017 regulation'), ('2021 regulation', '2021 regulation')], default='2017 regulation', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='First', max_length=50),
        ),
    ]
