# Generated by Django 4.1.7 on 2023-03-15 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_timetable_department_timetable_regulation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='info',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='staff_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='main.staff'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main.subject'),
        ),
        migrations.DeleteModel(
            name='TimeTableInfo',
        ),
    ]
