# Generated by Django 4.1.7 on 2023-03-15 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_department_name'),
        ('main', '0018_remove_timetable_info_timetable_day_and_more'),
    ]

    operations = [
    ]
