# Generated by Django 4.1.7 on 2023-03-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_merge_20230316_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='period_1',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_2',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_3',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_4',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_5',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_6',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_7',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='period_8',
        ),
        migrations.AddField(
            model_name='timetable',
            name='period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='regulation',
            field=models.CharField(choices=[('2017 regulation', '2017 regulation'), ('2021 regulation', '2021 regulation')], default='2017 regulation', max_length=100),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', max_length=50),
        ),
        migrations.AddField(
            model_name='timetable',
            name='staff_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='main.staff'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical and Electronic Engineering', 'EEE'), ('Mechanical Engineering', 'Mech'), ('Civil Engineering', 'Civil')], default='CSE', max_length=200),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], default='First', max_length=50),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
