# Generated by Django 4.1.7 on 2023-03-16 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_timetable_period_remove_timetable_staff_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period_8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('subject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Period_7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('subject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Period_6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('subject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Period_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('subject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Period_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.staff')),
                ('subject_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject')),
            ],
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period_4'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period_5'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period_6'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period_7'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.period_8'),
        ),
    ]
