# Generated by Django 4.1.7 on 2023-03-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_period_2_staff_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='regulation',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='staff_name',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='year',
        ),
        migrations.AlterField(
            model_name='timetable',
            name='subject_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='main.subject'),
        ),
    ]
