# Generated by Django 4.1.7 on 2023-03-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_timetable_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
