# Generated by Django 4.1.7 on 2023-03-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_studentattendance_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='period',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_1', to='main.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_2', to='main.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_3', to='main.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_4', to='main.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_5', to='main.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_6',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_6', to='main.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_7',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_7', to='main.subject'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='period_8',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='period_8', to='main.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical and Electronic Engineering', 'EEE'), ('Mechanical Engineering', 'Mech'), ('Civil Engineering', 'Civil')], default='CSE', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='regulation',
            field=models.CharField(choices=[('2017 regulation', '2017 regulation'), ('2021 regulation', '2021 regulation')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.CharField(choices=[('odd', 'Odd'), ('even', 'Even')], max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='staff',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.staff'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=100),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=50, null=True),
        ),
    ]
