# Generated by Django 4.1.7 on 2023-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_timetable_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'CSE'), ('Electronics and Communication Engineering', 'ECE'), ('Electrical and Electronic Engineering', 'EEE'), ('Mechanical Engineering', 'Mech'), ('Civil Engineering', 'Civil')], default='CSE', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='regulation',
            field=models.CharField(choices=[('2017 regulation', '2017 regulation'), ('2021 regulation', '2021 regulation')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='year',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=100, null=True),
        ),
    ]
