# Generated by Django 4.1.7 on 2023-03-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_timetable_department_timetable_regulation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentattendance',
            name='day',
        ),
        migrations.RemoveField(
            model_name='studentattendance',
            name='time',
        ),
        migrations.AlterField(
            model_name='studentattendance',
            name='mark_attendance',
            field=models.CharField(blank=True, choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Duty', 'On Duty')], max_length=100, null=True),
        ),
    ]
