# Generated by Django 4.2 on 2023-04-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentattendance',
            name='reason',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
